#!/usr/bin/env Rscript
# =============================================================================
# 02_pca_scatterplot.R
# PCA on Discordant Variant Concordance Matrix
#
# Reads the variant concordance matrix (generated by build_variant_table.sh),
# removes universally-concordant variants, runs PCA, plots scatterplot
# showing caller clustering.
#
# Adapted from: archive/caller_benchmark-main/benchmark_analysis.R (lines 1603–1652)
#
# Usage:
#   Rscript visualization/02_pca_scatterplot.R [concordance_tsv] [output_dir]
#   Rscript visualization/02_pca_scatterplot.R results/eval/vcfeval/variant_concordance_30x.tsv results/plots
# =============================================================================

suppressPackageStartupMessages({
  library(ggplot2)
  library(ggrepel)
  library(cowplot)
})

# ── Command-line args ──
args <- commandArgs(trailingOnly = TRUE)

project_dir <- normalizePath(file.path(dirname(sys.frame(1)$ofile %||% "."), ".."), mustWork = FALSE)
vcfeval_dir <- file.path(project_dir, "results", "eval", "vcfeval")

# Find all concordance files or use specified one
if (length(args) >= 1) {
  conc_files <- args[1]
} else {
  conc_files <- list.files(vcfeval_dir, pattern = "variant_concordance_.*\\.tsv$",
                           full.names = TRUE)
  if (length(conc_files) == 0) {
    stop("No concordance files found. Run build_variant_table.sh first.")
  }
}

output_dir <- if (length(args) >= 2) args[2] else file.path(project_dir, "results", "plots")
dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)

# ── Caller colors ──
caller_colors <- c(
  "HC" = "#E64B35", "DV" = "#4DBBD5", "ST" = "#00A087",
  "FB" = "#3C5488", "DS" = "#F39B7F"
)

# ── Process each concordance file ──
pca_plots <- list()

for (conc_file in conc_files) {
  cat("Processing:", basename(conc_file), "\n")

  # Extract coverage label
  cov_label <- gsub(".*concordance_(\\d+x)\\.tsv$", "\\1", basename(conc_file))

  # Read concordance matrix
  conc <- read.delim(conc_file, sep = "\t", header = TRUE, stringsAsFactors = FALSE)
  cat("  Variants:", nrow(conc), "\n")
  cat("  Columns: ", paste(colnames(conc), collapse = ", "), "\n")

  # Caller columns (exclude variant_id, truth)
  caller_cols <- setdiff(colnames(conc), c("variant_id", "truth"))
  cat("  Callers:  ", paste(caller_cols, collapse = ", "), "\n")

  if (length(caller_cols) < 2) {
    cat("  SKIP: fewer than 2 callers\n\n")
    next
  }

  # Binary matrix: callers only
  call_mat <- as.matrix(conc[, caller_cols])

  # Count how many callers called each variant
  n_callers_called <- rowSums(call_mat)
  n_total <- length(caller_cols)

  # ── Filter: remove concordant variants (all called or none called) ──
  # Keep only discordant variants (at least 1 but not all callers agree)
  discordant_mask <- n_callers_called > 0 & n_callers_called < n_total
  disc_mat <- call_mat[discordant_mask, ]

  cat("  Concordant (all agree):  ", sum(!discordant_mask), "\n")
  cat("  Discordant (disagree):   ", nrow(disc_mat), "\n")

  if (nrow(disc_mat) < 10) {
    cat("  SKIP: too few discordant variants for PCA\n\n")
    next
  }

  # ── Run PCA on transposed matrix (callers as observations) ──
  # Each caller becomes a point; dimensions = variants
  pca_out <- prcomp(t(disc_mat), center = TRUE, scale. = FALSE)
  pca_summary <- summary(pca_out)

  pc1_var <- round(pca_summary$importance["Proportion of Variance", "PC1"] * 100, 1)
  pc2_var <- round(pca_summary$importance["Proportion of Variance", "PC2"] * 100, 1)

  cat("  PC1 variance: ", pc1_var, "%\n")
  cat("  PC2 variance: ", pc2_var, "%\n")

  # Build plot dataframe
  pca_df <- as.data.frame(pca_out$x)
  pca_df$Caller <- rownames(pca_df)

  # ── Plot ──
  p <- ggplot(pca_df, aes(x = PC1, y = PC2, color = Caller, label = Caller)) +
    geom_point(size = 5) +
    geom_label_repel(
      size = 4, fontface = "bold",
      box.padding = 0.5, point.padding = 0.3,
      max.overlaps = 20
    ) +
    scale_color_manual(values = caller_colors, drop = FALSE) +
    labs(
      title = paste("PCA — Discordant Variants", cov_label),
      subtitle = paste0(nrow(disc_mat), " discordant variants out of ", nrow(call_mat), " total"),
      x = paste0("PC1 (", pc1_var, "%)"),
      y = paste0("PC2 (", pc2_var, "%)")
    ) +
    theme_bw(base_size = 13) +
    theme(
      panel.grid.minor = element_blank(),
      plot.title = element_text(hjust = 0.5, face = "bold"),
      plot.subtitle = element_text(hjust = 0.5, color = "gray40"),
      legend.position = "none"
    )

  pca_plots[[cov_label]] <- p

  # Save individual
  ggsave(file.path(output_dir, paste0("pca_scatterplot_", cov_label, ".pdf")),
         p, width = 7, height = 6)
  ggsave(file.path(output_dir, paste0("pca_scatterplot_", cov_label, ".png")),
         p, width = 7, height = 6, dpi = 150)
  cat("  Saved: pca_scatterplot_", cov_label, ".pdf/png\n\n", sep = "")
}

# ── Combined panel across coverages ──
if (length(pca_plots) > 1) {
  n_plots <- length(pca_plots)
  ncol_grid <- min(n_plots, 2)
  combined <- plot_grid(plotlist = pca_plots, ncol = ncol_grid,
                        labels = letters[1:n_plots])
  ggsave(file.path(output_dir, "pca_scatterplot_combined.pdf"),
         combined, width = 7 * ncol_grid, height = 6 * ceiling(n_plots / ncol_grid))
  ggsave(file.path(output_dir, "pca_scatterplot_combined.png"),
         combined, width = 7 * ncol_grid, height = 6 * ceiling(n_plots / ncol_grid), dpi = 150)
  cat("Saved: pca_scatterplot_combined.pdf/png\n")
}

cat("\n✓ PCA scatterplot analysis complete.\n")
cat("  Output directory:", output_dir, "\n")
